sonar.projectKey=farooq831_cohort-9-mern-11237-muhammad
sonar.organization=farooq831
sonar.projectName=Notes App Backend

sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**

sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io