sonar.projectKey=cohort-9-mern-11237-muhammad-backend
sonar.projectName=Notes App Backend

sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**

sonar.sourceEncoding=UTF-8
sonar.javascript.node.maxspace=4096